replicaCount: 1

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9093"

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 500Mi

config:
  enabled: true
  global: {}
    # slack_api_url: ''
  templates:
    - '/etc/alertmanager/*.tmpl'

  receivers:
    - name: 'default-receiver'
    - name: 'telegram'
      telegram_configs:
      - api_url: 'https://api.telegram.org'
        bot_token: '7854226917:AAETlZt4pHu-ZE8Aq2uqB98QwUiwpl0ze8k'
        chat_id: '-4513763724'
        message: "Alertmanager\n--\n Alertname: {{ .GroupLabels.alertname}}\n Severity: {{ .CommonLabels.severity }}\n {{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"

  # route:
  #   group_by: ['critical']
  #   receiver: 'default-receiver'
  #   group_wait: 10s
  #   group_interval: 5m
  #   repeat_interval: 3h
  #   routes:
  #     - receiver: 'telegram'
  #       continue: true

  route:
    receiver: 'default-receiver'
    group_by: ['critical']
    group_wait: 5s
    group_interval: 5m
    repeat_interval: 3h
    routes:
      - receiver: 'telegram'
        matchers: [ severity = "critical" ]
        continue: true