image: "docker.io/elasticsearch"
imageTag: "8.5.1"
imagePullPolicy: "IfNotPresent"

replicas: 2
minimumMasterNodes: 1

secret:
  enabled: true
  password: "" # generated randomly if not defined

resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "2000m"
    memory: "4Gi"

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi