server:
  datasource:
    url: "http://vm-cluster-victoria-metrics-cluster-vmselect:8481/select/0/prometheus/"

  notifier:
    alertmanager:
      url: "alertmanager:9093"

  config:
    alerts:
      groups:
        - name: common
          rules:
            - alert: instanceIsDown
              for: 1m
              expr: up == 0
              labels:
                severity: critical
              annotations:
                summary: "{{ $labels.job }} instance: {{$labels.instance }} is not up"
                description: "Job {{ $labels.job }}  instance: {{$labels.instance }} is not up for the last 1 minute"
