server:
  datasource:
    url: "http://vm-cluster-victoria-metrics-cluster-vmselect:8481/select/0/prometheus/"

  replicaCount: 1

  notifier:
    alertmanager:
      url: "alertmanager:9093"

  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

  podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8880"

  config:
    alerts:
      groups:
        - name: common
          rules:
            - alert: instanceIsDown
              for: 1m
              expr: up == 0
              labels:
                severity: critical
              annotations:
                summary: "{{ $labels.job }} instance: {{$labels.instance }} is not up"
                description: "Job {{ $labels.job }}  instance: {{$labels.instance }} is not up for the last 1 minute"
