server:
  datasource:
    url: "http://vm-cluster-victoria-metrics-cluster-vmselect:8481/select/0/prometheus/"

  replicaCount: 1

  notifier:
    alertmanager:
      url: "http://vm-alertmanager:9093"

  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

  podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8880"

  config:
    alerts:
      groups:
        - name: common
          rules:
            - alert: instanceIsDown
              for: 1m
              expr: up == 0
              labels:
                severity: critical
              annotations:
                summary: "{{ $labels.job }} instance: {{$labels.instance }} is not up"
                description: "Job {{ $labels.job }}  instance: {{$labels.instance }} is not up for the last 1 minute"
            - alert: HostHighCpuLoad
              expr: (sum by (instance) (avg by (mode, instance) (rate(node_cpu_seconds_total{mode!="idle"}[2m]))) > 0.8) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
              for: 10m
              labels:
                severity: warning
              annotations:
                summary: Host high CPU load (instance {{ $labels.instance }})
                description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
            - alert: HostCpuIsUnderutilized
              expr: (100 - (rate(node_cpu_seconds_total{mode="idle"}[30m]) * 100) < 20) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
              for: 1w
              labels:
                severity: info
              annotations:
                summary: Host CPU is underutilized (instance {{ $labels.instance }})
                description: "CPU load is < 20% for 1 week. Consider reducing the number of CPUs.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
            - alert: HostCpuHighIowait
              expr: (avg by (instance) (rate(node_cpu_seconds_total{mode="iowait"}[5m])) * 100 > 10) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
              for: 0m
              labels:
                severity: warning
              annotations:
                summary: Host CPU high iowait (instance {{ $labels.instance }})
                description: "CPU iowait > 10%. A high iowait means that you are disk or network bound.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
